<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>CustomPortRifts</AssemblyName>
    <Product>Custom PortRifts</Product>
    <Version>2.1.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>CustomPortRifts</RootNamespace>
    <Authors>96 LB</Authors>
    <Description>Rift of the NecroDancer mod for customizing in-game character portraits</Description>
    <PackageProjectUrl></PackageProjectUrl>
    <RepositoryUrl>https://github.com/96-LB/CustomPortRifts</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.43" IncludeAssets="compile" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>lib\RiftOfTheNecroDancer.dll</HintPath>
    </Reference>
    <Reference Include="Coffee.SoftMaskForUGUI">
      <HintPath>lib\Coffee.SoftMaskForUGUI.dll</HintPath>
    </Reference>
    <Reference Include="RiftOfTheNecroManager">
      <HintPath>lib\RiftOfTheNecroManager.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>lib\Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>lib\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="FMODUnity">
      <HintPath>lib\FMODUnity.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>